"""
fake_customers_generation.py

Gera um dataset de vendas fictícias para teste, considerando:
- Probabilidades diferenciadas para produtos já comprados,
- Preferências regionais (lista de produtos por localidade),
- Quantidades e feedback simulados,
- Datas randômicas dentro de um período.
"""

import random
import pandas as pd

# === Configurações de geração ===
NUM_ORDERS_PER_CLIENT = 100  # Quantidade de pedidos por cliente
MAX_DATE_OFFSET_DAYS = 365  # Intervalo máximo para datas futuras
OUTPUT_CSV_PATH = "data/sells_data.csv"  # Caminho de saída

# === Definição de entidades ===
# (Listas completas omitidas para brevidade)
CLIENTS = [  # lista de nomes de clientes
    "Ana",
    "Beatriz",
    "Camila",
    "Daniela",
    "Elisa",
    "Fernanda",
    "Gabriela",
    "Heloísa",
    "Isabela",
    "Júlia",
    "Juliana",
    "Larissa",
    "Mariana",
    "Natália",
    "Olívia",
    "Patrícia",
    "Rafaela",
    "Sabrina",
    "Tatiane",
    "Vanessa",
    "Yasmin",
    "Mônica",
    "Débora",
    "Cíntia",
    "Érica",
    "André",
    "Bruno",
    "Caio",
    "Diego",
    "Eduardo",
    "Felipe",
    "Gabriel",
    "Henrique",
    "Igor",
    "João",
    "Lucas",
    "Leandro",
    "Marcelo",
    "Nicolas",
    "Otávio",
    "Paulo",
    "Rafael",
    "Sérgio",
    "Tiago",
    "Vinícius",
    "Alexandre",
    "Gustavo",
    "Matheus",
    "Pedro",
    "Rodrigo",
]

PRODUCTS = [  # lista de produtos disponíveis
    "Abacate",
    "Abacaxi",
    "Abóbora",
    "Abóbora italiana",
    "Abóbora japonesa - Tetsukabut",
    "Abóbora menina",
    "Acerola",
    "Agrião",
    "Alface",
    "Alho",
    "Atemóia",
    "Banana",
    "Batata",
    "Batata-doce",
    "Berinjela",
    "Beterraba",
    "Brazlândia",
    "Brócolis - Cabeça Única",
    "Brócolis - Ramoso",
    "Cajamanga",
    "Caqui",
    "Cebola",
    "Cebolinha",
    "Ceilândia",
    "Cenoura",
    "Chuchu",
    "Coco",
    "Coentro",
    "Couve",
    "Couve-flor",
    "Gama",
    "Gengibre",
    "Goiaba",
    "Graviola",
    "Jabuticaba",
    "Jardim",
    "Jiló",
    "Laranja",
    "Lichia",
    "Limão",
    "Mamão",
    "Mandioca",
    "Manga",
    "Maracujá",
    "Maracujá Pérola",
    "Milho doce",
    "Milho-verde",
    "Mirtilo",
    "Morango",
    "PAD-DF",
    "Paranoá",
    "Pepino",
    "Pimentão",
    "Pipiripau",
    "Pitaia",
    "Planaltina",
    "Quiabo",
    "Repolho",
    "Rio Preto",
    "Sobradinho",
    "São Sebastião",
    "Tabatinga",
    "Tangerina",
    "Taquara",
    "Tomate",
    "Uva",
    "Uva Vinífera",
    "Vargem Bonita",
]

ORIGINAL_LOCATIONS = [  # lista de localidades
    "Alexandre Gusmão",
    "Brazlândia",
    "Ceilândia",
    "Gama",
    "Jardim",
    "PAD-DF",
    "Paranoá",
    "Pipiripau",
    "Planaltina",
    "Rio Preto",
    "Sobradinho",
    "São Sebastião",
    "Tabatinga",
    "Taquara",
    "Vargem Bonita",
]

LOCATIONS_PRODUCTS = {  # mapeia cada localidade a seus produtos típicos
    "Alexandre Gusmão": [
        "Goiaba",
        "Abacate",
        "Tangerina",
        "Limão",
        "Banana",
        "Graviola",
        "Maracujá",
        "Manga",
        "Atemóia",
        "Uva",
        "Brazlândia",
        "Alface",
        "Mandioca",
        "Brócolis - Cabeça Única",
        "Repolho",
        "Couve",
        "Cebolinha",
        "Tomate",
        "Chuchu",
        "Brócolis - Ramoso",
        "Pimentão",
        "Brazlândia",
    ],
    "Brazlândia": [
        "Goiaba",
        "Abacate",
        "Limão",
        "Tangerina",
        "Banana",
        "Atemóia",
        "Maracujá",
        "Manga",
        "Uva",
        "Cajamanga",
        "Ceilândia",
        "Morango",
        "Alface",
        "Repolho",
        "Abóbora italiana",
        "Mandioca",
        "Brócolis - Cabeça Única",
        "Chuchu",
        "Tomate",
        "Pimentão",
        "Couve",
        "Ceilândia",
    ],
    "Ceilândia": [
        "Banana",
        "Limão",
        "Abacate",
        "Tangerina",
        "Maracujá",
        "Manga",
        "Laranja",
        "Goiaba",
        "Coco",
        "Acerola",
        "Gama",
        "Alface",
        "Mandioca",
        "Milho-verde",
        "Brócolis - Cabeça Única",
        "Repolho",
        "Brócolis - Ramoso",
        "Batata-doce",
        "Chuchu",
        "Couve",
        "Tomate",
        "Gama",
    ],
    "Gama": [
        "Limão",
        "Abacate",
        "Banana",
        "Tangerina",
        "Manga",
        "Acerola",
        "Pitaia",
        "Maracujá",
        "Laranja",
        "Lichia",
        "Jardim",
        "Alface",
        "Mandioca",
        "Milho-verde",
        "Coentro",
        "Brócolis - Cabeça Única",
        "Couve",
        "Cebolinha",
        "Brócolis - Ramoso",
        "Repolho",
        "Pimentão",
        "Jardim",
    ],
    "Jardim": [
        "Maracujá",
        "Uva Vinífera",
        "Limão",
        "Tangerina",
        "Graviola",
        "Banana",
        "Abacate",
        "Goiaba",
        "Mamão",
        "PAD-DF",
        "Cenoura",
        "Cebola",
        "Abóbora japonesa - Tetsukabut",
        "Tomate",
        "Beterraba",
        "Batata-doce",
        "Mandioca",
        "Repolho",
        "Pimentão",
        "Berinjela",
        "PAD-DF",
    ],
    "PAD-DF": [
        "Uva Vinífera",
        "Uva",
        "Abacate",
        "Limão",
        "Maracujá",
        "Banana",
        "Manga",
        "Tangerina",
        "Mamão",
        "Laranja",
        "Paranoá",
        "Tomate",
        "Milho doce",
        "Cenoura",
        "Cebola",
        "Pepino",
        "Mandioca",
        "Alface",
        "Pimentão",
        "Repolho",
        "Berinjela",
        "Paranoá",
    ],
    "Paranoá": [
        "Banana",
        "Limão",
        "Manga",
        "Uva",
        "Abacate",
        "Tangerina",
        "Goiaba",
        "Maracujá",
        "Laranja",
        "Maracujá Pérola",
        "Pipiripau",
        "Alface",
        "Milho-verde",
        "Mandioca",
        "Beterraba",
        "Tomate",
        "Quiabo",
        "Pimentão",
        "Repolho",
        "Berinjela",
        "Chuchu",
        "Pipiripau",
    ],
    "Pipiripau": [
        "Laranja",
        "Banana",
        "Limão",
        "Lichia",
        "Goiaba",
        "Abacate",
        "Pitaia",
        "Maracujá",
        "Tangerina",
        "Uva",
        "Planaltina",
        "Batata",
        "Mandioca",
        "Tomate",
        "Pimentão",
        "Abóbora",
        "Cenoura",
        "Pepino",
        "Abóbora italiana",
        "Berinjela",
        "Chuchu",
        "Planaltina",
    ],
    "Planaltina": [
        "Limão",
        "Banana",
        "Lichia",
        "Abacate",
        "Tangerina",
        "Manga",
        "Uva",
        "Maracujá",
        "Laranja",
        "Goiaba",
        "Rio Preto",
        "Milho-verde",
        "Mandioca",
        "Batata-doce",
        "Tomate",
        "Alface",
        "Cebolinha",
        "Repolho",
        "Pimentão",
        "Chuchu",
        "Couve",
        "Rio Preto",
    ],
    "Rio Preto": [
        "Abacate",
        "Tangerina",
        "Banana",
        "Limão",
        "Maracujá",
        "Jabuticaba",
        "Manga",
        "Pitaia",
        "Graviola",
        "Laranja",
        "São Sebastião",
        "Alho",
        "Mandioca",
        "Abóbora japonesa - Tetsukabut",
        "Batata-doce",
        "Beterraba",
        "Abóbora",
        "Tomate",
        "Pimentão",
        "Cenoura",
        "Repolho",
        "São Sebastião",
    ],
    "São Sebastião": [
        "Maracujá",
        "Manga",
        "Banana",
        "Limão",
        "Maracujá Pérola",
        "Tangerina",
        "Abacate",
        "Laranja",
        "Abacaxi",
        "Pitaia",
        "Sobradinho",
        "Cebola",
        "Mandioca",
        "Alface",
        "Abóbora",
        "Morango",
        "Quiabo",
        "Couve",
        "Tomate",
        "Agrião",
        "Repolho",
        "Sobradinho",
    ],
    "Sobradinho": [
        "Banana",
        "Abacate",
        "Manga",
        "Limão",
        "Uva",
        "Tangerina",
        "Maracujá",
        "Mirtilo",
        "Laranja",
        "Maracujá Pérola",
        "Tabatinga",
        "Mandioca",
        "Alface",
        "Repolho",
        "Brócolis - Ramoso",
        "Tomate",
        "Couve",
        "Couve-flor",
        "Berinjela",
        "Pimentão",
        "Chuchu",
        "Tabatinga",
    ],
    "Tabatinga": [
        "Abacate",
        "Limão",
        "Maracujá",
        "Tangerina",
        "Banana",
        "Goiaba",
        "Maracujá Pérola",
        "Pitaia",
        "Manga",
        "Uva",
        "Taquara",
        "Batata-doce",
        "Mandioca",
        "Cenoura",
        "Cebola",
        "Abóbora japonesa - Tetsukabut",
        "Beterraba",
        "Jiló",
        "Repolho",
        "Chuchu",
        "Tomate",
        "Taquara",
    ],
    "Taquara": [
        "Banana",
        "Tangerina",
        "Abacate",
        "Maracujá",
        "Limão",
        "Laranja",
        "Manga",
        "Pitaia",
        "Caqui",
        "Acerola",
        "Vargem Bonita",
        "Mandioca",
        "Abóbora menina",
        "Pimentão",
        "Tomate",
        "Abóbora italiana",
        "Berinjela",
        "Pepino",
        "Couve-flor",
        "Repolho",
        "Chuchu",
        "Vargem Bonita",
    ],
    "Vargem Bonita": [
        "Banana",
        "Abacate",
        "Limão",
        "Manga",
        "Uva",
        "Pitaia",
        "Tangerina",
        "Maracujá",
        "Maracujá Pérola",
        "Laranja",
        "Alface",
        "Mandioca",
        "Milho-verde",
        "Gengibre",
        "Couve",
        "Brócolis - Cabeça Única",
        "Repolho",
        "Cebolinha",
        "Brócolis - Ramoso",
        "Pimentão",
    ],
}

# Opções de feedback possíveis
FEEDBACK_OPTIONS = ["Excelente", "Bom", "Regular", "Ruim", "Péssimo"]


def generate_fake_sales() -> list[dict]:
    """
    Gera registros de vendas fictícias:
    - Cada cliente recebe NUM_ORDERS_PER_CLIENT entradas.
    - Produtos com histórico ou típicos da localidade têm maior probabilidade.
    - Quantidades são maiores para produtos regionais.
    - Datas são offset aleatório até MAX_DATE_OFFSET_DAYS dias.

    Retorna:
        Listagem de dicionários prontos para DataFrame.
    """
    sells = []
    base_date = pd.Timestamp.now().normalize()

    for idx, client in enumerate(CLIENTS):
        # Atribui localidade de forma cíclica
        location = ORIGINAL_LOCATIONS[idx % len(ORIGINAL_LOCATIONS)]

        # Histórico de produtos comprados para o cliente
        client_history = []

        for _ in range(NUM_ORDERS_PER_CLIENT):
            # Calcula pesos para escolha de produto
            weights = [
                100
                if p in client_history
                else 25
                if p in LOCATIONS_PRODUCTS.get(location, [])
                else 1
                for p in PRODUCTS
            ]
            product = random.choices(PRODUCTS, weights=weights, k=1)[0]

            # Define quantidade com base em regionalidade
            if product in LOCATIONS_PRODUCTS.get(location, []):
                quantity = random.randint(50, 100)
            else:
                quantity = random.randint(1, 10)

            # Simula data com deslocamento aleatório
            date = (
                base_date
                + pd.Timedelta(days=random.randint(0, MAX_DATE_OFFSET_DAYS))
                + pd.Timedelta(hours=random.randint(0, 23))
                + pd.Timedelta(minutes=random.randint(0, 59))
            )

            # Cria registro e atualiza histórico
            record = {
                "client": client,
                "location": location,
                "product": product,
                "quantity": quantity,
                "customerFeedback": random.choice(FEEDBACK_OPTIONS),
                "date": date,
            }
            sells.append(record)
            client_history.append(product)

    return sells


if __name__ == "__main__":
    # Gera dados e salva em CSV
    df_sales = pd.DataFrame(generate_fake_sales())
    df_sales.to_csv(OUTPUT_CSV_PATH, index=False, encoding="utf-8-sig")
    print(f"Geração de dados concluída. Arquivo salvo em '{OUTPUT_CSV_PATH}'.")
